from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey, Text, DateTime
from .database import Base
class User(Base):
    __tablename__="users"
    id=Column(Integer, primary_key=True, index=True)
    full_name=Column(String(255), nullable=False)
    email=Column(String(255), unique=True, index=True, nullable=False)
    password_hash=Column(String(255), nullable=False)
    is_admin=Column(Boolean, default=False, nullable=False)
class Question(Base):
    __tablename__="questions"
    id=Column(Integer, primary_key=True, index=True)
    question_code=Column(String(100), unique=True, index=True, nullable=False)
    track=Column(String(100), nullable=False, index=True)
    level=Column(Integer, nullable=False, index=True)
    section=Column(String(50), nullable=False, index=True)
    difficulty=Column(Integer, default=1, nullable=False)
    weight=Column(Float, default=1.0, nullable=False)
    question_text=Column(Text, nullable=False)
    option_a=Column(Text, nullable=False)
    option_b=Column(Text, nullable=False)
    option_c=Column(Text, nullable=False)
    option_d=Column(Text, nullable=False)
    correct_option=Column(String(1), nullable=False)
    active=Column(Boolean, default=True, nullable=False)
class ExamAttempt(Base):
    __tablename__="exam_attempts"
    id=Column(Integer, primary_key=True, index=True)
    user_id=Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    track=Column(String(100), nullable=False, index=True)
    attempted_level=Column(Integer, nullable=False)
    exam_name=Column(String(255))
    status=Column(String(50), default="mcq_in_progress", nullable=False)
    current_index=Column(Integer, default=0, nullable=False)
    total_questions=Column(Integer, default=20, nullable=False)
    raw_score=Column(Integer, default=0, nullable=False)
    percent_score=Column(Float, default=0.0, nullable=False)
    achieved_level=Column(Integer, default=0, nullable=False)
    passed=Column(Boolean, default=False, nullable=False)
    business_score=Column(Float, default=0.0, nullable=False)
    functional_score=Column(Float, default=0.0, nullable=False)
    technical_score=Column(Float, default=0.0, nullable=False)
    mcq_percent=Column(Float, default=0.0, nullable=False)
    essay_percent=Column(Float, default=0.0, nullable=False)
    scenario_percent=Column(Float, default=0.0, nullable=False)
    essay_prompt=Column(Text)
    essay_response=Column(Text)
    essay_feedback=Column(Text)
    scenario_prompt=Column(Text)
    scenario_response=Column(Text)
    scenario_feedback=Column(Text)
    started_at=Column(DateTime, default=datetime.utcnow, nullable=False)
    submitted_at=Column(DateTime)
class ExamAnswer(Base):
    __tablename__="exam_answers"
    id=Column(Integer, primary_key=True, index=True)
    attempt_id=Column(Integer, ForeignKey("exam_attempts.id"), nullable=False, index=True)
    question_id=Column(Integer, ForeignKey("questions.id"), nullable=False, index=True)
    selected_option=Column(String(1), nullable=False)
    is_correct=Column(Boolean, default=False, nullable=False)
    section=Column(String(50), nullable=False)
    score_awarded=Column(Float, default=0.0, nullable=False)
class Certificate(Base):
    __tablename__="certificates"
    id=Column(Integer, primary_key=True, index=True)
    user_id=Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    attempt_id=Column(Integer, ForeignKey("exam_attempts.id"), nullable=False, index=True)
    track=Column(String(100), nullable=False)
    certified_level=Column(Integer, nullable=False)
    certificate_code=Column(String(100), unique=True, index=True, nullable=False)
    issued_at=Column(DateTime, default=datetime.utcnow, nullable=False)
